Repository MycroftAI/lingua-franca, pull requests merged in 2019-12, with the labels that each got.

#41 remove annotate methods (accidental commit)
  lingua_franca/lang/parse_en.py
  lingua_franca/parse.py
Labels: CLA: Yes

#47 add some more time idioms
  lingua_franca/lang/format_de.py
  lingua_franca/lang/format_en.py
  test/test_format.py
  test/test_format_de.py
Labels: CLA: Yes

#10 handle extracting "tonight"/"at night"
  lingua_franca/lang/parse_en.py
  test/test_parse.py
Labels: CLA: Yes, bug, en

#55 Rebase of Universal normalizer
  lingua_franca/lang/parse_common.py
  lingua_franca/lang/parse_en.py
  lingua_franca/lang/parse_pt.py
  lingua_franca/res/text/en-us/normalize.json
  lingua_franca/res/text/pt-pt/normalize.json
  test/test_parse_pt.py
Labels: CLA: Yes, en, enhancement, pt

#54 Sync swedish changes from mycroft core
  lingua_franca/format.py
  lingua_franca/lang/format_sv.py
  lingua_franca/lang/parse_sv.py
  test/test_format_sv.py
Labels: CLA: Yes, sv

#56 Add Dutch updates from mycroft-core
  lingua_franca/lang/common_data_nl.py
  lingua_franca/lang/format_nl.py
  lingua_franca/lang/parse_nl.py
  lingua_franca/parse.py
  test/test_parse_nl.py
Labels: CLA: Yes, nl

#32 port extractnumber-es fixes from mycroft-core
  lingua_franca/lang/parse_es.py
  lingua_franca/parse.py
  test/test_parse_es.py
Labels: CLA: Yes, es

#52 Bug/extract number en handle "nth"
  lingua_franca/lang/parse_en.py
  test/test_parse.py
Labels: CLA: Yes, bug, en

#4 pronounce ordinals
  lingua_franca/format.py
  lingua_franca/lang/common_data_en.py
  lingua_franca/lang/format_en.py
  test/test_format.py
Labels: CLA: Yes, en, enhancement

#40 Bugfix/hyphenated duration
  lingua_franca/lang/parse_en.py
  test/test_parse.py
Labels: CLA: Yes, bug, en

#39 Bugfix/extract datetime bugs
  lingua_franca/lang/parse_en.py
  test/test_parse.py
Labels: CLA: Yes, bug, en

#58 Workaround for "May I..." in extract_datetime_en
  lingua_franca/lang/parse_en.py
  test/test_parse.py
Labels: CLA: Yes

#57 Add default value to `denominator`
  lingua_franca/lang/format_common.py
  lingua_franca/lang/format_da.py
  lingua_franca/lang/format_de.py
  lingua_franca/lang/format_en.py
  lingua_franca/lang/format_es.py
  lingua_franca/lang/format_fr.py
  lingua_franca/lang/format_hu.py
  lingua_franca/lang/format_it.py
  lingua_franca/lang/format_pt.py
  test/test_format_common.py
Labels: CLA: Yes

#60 extract_date_time - 'next {day}' to be 3-9 days in future
  lingua_franca/lang/parse_en.py
  test/test_parse.py
Labels: CLA: Yes

#48 cleanup python2 unicode
  lingua_franca/lang/common_data_en.py
  lingua_franca/lang/common_data_es.py
  lingua_franca/lang/common_data_pt.py
  lingua_franca/lang/format_common.py
  lingua_franca/lang/format_da.py
  lingua_franca/lang/format_es.py
  lingua_franca/lang/format_fr.py
  lingua_franca/lang/format_hu.py
  lingua_franca/lang/format_it.py
  lingua_franca/lang/format_pt.py
  lingua_franca/lang/parse_common.py
  lingua_franca/lang/parse_da.py
  lingua_franca/lang/parse_de.py
  lingua_franca/lang/parse_en.py
  lingua_franca/lang/parse_es.py
  lingua_franca/lang/parse_fr.py
  lingua_franca/lang/parse_it.py
  lingua_franca/lang/parse_pt.py
  lingua_franca/parse.py
  lingua_franca/time.py
  test/test_format_da.py
  test/test_format_es.py
  test/test_format_fr.py
  test/test_format_hu.py
  test/test_format_it.py
  test/test_format_nl.py
  test/test_format_pt.py
  test/test_parse.py
  test/test_parse_da.py
  test/test_parse_de.py
  test/test_parse_es.py
  test/test_parse_fr.py
  test/test_parse_it.py
  test/test_parse_pt.py
  test/test_parse_sv.py
Labels: CLA: Yes

#63 Remove Python 3.4 from autotest and add Python 3.8
  .travis.yml
Labels: CLA: Yes
