Repository MycroftAI/lingua-franca, pull requests merged in 2020-11, with the labels that each got.

#141 Add Python3.9 to tested versions and bump version number
  .travis.yml
  setup.py
Labels: CLA: Yes

#113 Initial polish support
  lingua_franca/format.py
  lingua_franca/internal.py
  lingua_franca/lang/common_data_pl.py
  lingua_franca/lang/format_pl.py
  lingua_franca/lang/parse_pl.py
  lingua_franca/parse.py
  lingua_franca/res/text/pl-pl/and.word
  lingua_franca/res/text/pl-pl/day.word
  lingua_franca/res/text/pl-pl/days.word
  lingua_franca/res/text/pl-pl/hour.word
  lingua_franca/res/text/pl-pl/hours.word
  lingua_franca/res/text/pl-pl/minute.word
  lingua_franca/res/text/pl-pl/minutes.word
  lingua_franca/res/text/pl-pl/or.word
  lingua_franca/res/text/pl-pl/second.word
  lingua_franca/res/text/pl-pl/seconds.word
  test/test_format_pl.py
  test/test_parse_pl.py
Labels: CLA: Yes, pl

#144 test_format_cs: remove testing for other languages
  test/test_format_cs.py
Labels: CLA: Yes, bug, cs

#151 Fix/deprwarn bugs
  lingua_franca/format.py
  lingua_franca/internal.py
  lingua_franca/parse.py
Labels: CLA: Yes

#148 explicitly add files to source dist package
  MANIFEST.in
  setup.py
Labels: CLA: Yes, bug

#157 Add Jenkinsfile for CLA check
  Jenkinsfile
Labels: CLA: Yes

#154 Add a Github Action for pytest
  .github/workflows/pytest.yml
  .travis.yml
  test/test_format_nl.py
Labels: CLA: Yes

#156 Added extract_duration support for dutch
  lingua_franca/lang/parse_nl.py
  test/test_parse_nl.py
Labels: CLA: Yes, enhancement, nl

#136 Support for formatting Slovenian
  lingua_franca/internal.py
  lingua_franca/lang/common_data_sl.py
  lingua_franca/lang/format_sl.py
  lingua_franca/lang/parse_sl.py
  lingua_franca/res/text/sl-si/and.word
  lingua_franca/res/text/sl-si/date_time.json
  lingua_franca/res/text/sl-si/date_time_test.json
  lingua_franca/res/text/sl-si/day.word
  lingua_franca/res/text/sl-si/days.word
  lingua_franca/res/text/sl-si/hour.word
  lingua_franca/res/text/sl-si/hours.word
  lingua_franca/res/text/sl-si/minute.word
  lingua_franca/res/text/sl-si/minutes.word
  lingua_franca/res/text/sl-si/normalize.json
  lingua_franca/res/text/sl-si/or.word
  lingua_franca/res/text/sl-si/second.word
  lingua_franca/res/text/sl-si/seconds.word
  test/test_format_sl.py
Labels: CLA: Yes, hacktoberfest-accepted, sl

#158 config.load_langs_on_demand: permits on-the-fly loading/unloading, to facilitate proc-gen use cases
  lingua_franca/__init__.py
  lingua_franca/config.py
  lingua_franca/internal.py
  test/test_localizer.py
Labels: CLA: Yes, enhancement, multi_lang
