Repository MycroftAI/lingua-franca, pull requests merged in 2020-01, with the labels that each got.

#62 Add fixes to spanish by ChanceNCounter
  lingua_franca/lang/parse_es.py
  test/test_parse_es.py
Labels: CLA: Yes, bug, es

#61 split % and # while tokenizing
  lingua_franca/lang/parse_common.py
  lingua_franca/lang/parse_pt.py
  test/test_parse.py
  test/test_parse_common.py
Labels: CLA: Yes, bug, en, pt

#68 fix breaking bug in parse_es test
  test/test_parse_es.py
Labels: CLA: Yes, bug

#38 bugfix/ handle "yesterday"/ "X days ago"
  lingua_franca/lang/parse_en.py
  test/test_parse.py
Labels: CLA: Yes, bug, en

#77 Fix/extractnumber incompatibility
  lingua_franca/lang/parse_da.py
  lingua_franca/lang/parse_de.py
  lingua_franca/lang/parse_es.py
  lingua_franca/lang/parse_fr.py
  lingua_franca/lang/parse_pt.py
  lingua_franca/lang/parse_sv.py
  test/test_parse_fr.py
Labels: CLA: Yes

#76 fix #75 pronounce_number fails on num < 1.0
  lingua_franca/lang/format_en.py
  lingua_franca/lang/format_es.py
  lingua_franca/lang/format_fr.py
  lingua_franca/lang/format_it.py
  lingua_franca/lang/format_pt.py
  test/test_format.py
  test/test_format_es.py
  test/test_format_fr.py
  test/test_format_it.py
  test/test_format_pt.py
Labels: CLA: Yes, en, es, fr, it, pt
