Repository MycroftAI/lingua-franca, pull requests merged in 2020-12, with the labels that each got.

#161 Add Catalan support to Lingua Franca
  lingua_franca/format.py
  lingua_franca/internal.py
  lingua_franca/lang/common_data_ca.py
  lingua_franca/lang/format_ca.py
  lingua_franca/lang/parse_ca.py
  lingua_franca/res/text/ca-es/and.word
  lingua_franca/res/text/ca-es/date_time.json
  lingua_franca/res/text/ca-es/date_time_test.json
  lingua_franca/res/text/ca-es/day.word
  lingua_franca/res/text/ca-es/days.word
  lingua_franca/res/text/ca-es/hour.word
  lingua_franca/res/text/ca-es/hours.word
  lingua_franca/res/text/ca-es/minute.word
  lingua_franca/res/text/ca-es/minutes.word
  lingua_franca/res/text/ca-es/normalize.json
  lingua_franca/res/text/ca-es/or.word
  lingua_franca/res/text/ca-es/second.word
  lingua_franca/res/text/ca-es/seconds.word
  test/test_format_ca.py
  test/test_parse_ca.py
Labels: CLA: Yes, ca, enhancement, refactor

#164 drop support for python 3.5 (EOL)
  .github/workflows/pytest.yml
  lingua_franca/internal.py
  setup.py
  test/test_localizer.py
Labels: CLA: Yes

#165 Add extract_duration for french
  lingua_franca/lang/parse_fr.py
  test/test_parse_fr.py
Labels: CLA: Yes

#146 bug fix #145 #143 #135 #153
  lingua_franca/lang/common_data_en.py
  lingua_franca/lang/parse_en.py
  test/test_parse.py
Labels: CLA: Yes, bug, en

#163 add file to credit "pre-spinoff" contributors
  pre-spinoff-credits.md
  readme.md
Labels: CLA: Yes

#168 Add date_time for french language
  lingua_franca/res/text/fr-fr/date_time.json
  lingua_franca/res/text/fr-fr/date_time_test.json
Labels: CLA: Yes
