Repository MycroftAI/lingua-franca, pull requests merged in 2022-07, with the labels that each got.

#221 Add detail on supported durations to extract_duration
  lingua_franca/lang/parse_cs.py
  lingua_franca/lang/parse_de.py
  lingua_franca/lang/parse_fa.py
  lingua_franca/lang/parse_fr.py
  lingua_franca/lang/parse_nl.py
  lingua_franca/lang/parse_pl.py
  lingua_franca/parse.py
Labels: CLA: Yes, documentation

#217 Remove random commented out code
  test/test_format.py
  test/test_format_cs.py
  test/test_format_da.py
  test/test_format_de.py
  test/test_format_fa.py
  test/test_format_fr.py
  test/test_format_hu.py
  test/test_format_nl.py
  test/test_format_sl.py
  test/test_format_sv.py
Labels: CLA: Yes, refactor

#230 Fix default_time argument on extract_datetime
  lingua_franca/lang/parse_en.py
  test/test_parse.py
Labels: bug, CLA: Yes

#235 Fix CICD job on master: Only update mycroft-core after tag and release
  .github/workflows/push.yml
Labels: bug, CLA: Yes
